#!/bin/bash
set -e;

# Check if name is specified
if [[ $1 == mariadb:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
    if [[ ! -d "$PLUGIN_PATH/link" ]]; then
        echo "Link plugin not found... Did you install it from https://github.com/rlaneve/dokku-link?"
        exit 1
    fi

    PLUGIN_NAME="mariadb"
    CONTAINER_NAME="${PLUGIN_NAME}_${APP}"
    HOST_DIR="$DOKKU_ROOT/$APP/$PLUGIN_NAME"
    ENVVAR_NAME="DATABASE_URL"
fi

case "$1" in
  mariadb:create)
    # Check if MariaDB container is installed
    IMAGE=$(docker images | grep "partlab/ubuntu-mariadb" | awk '{print $3}')
    if [[ -z $IMAGE ]]; then
        echo "MariaDB image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi

    # Stop existing container with the same persistent MariaDB
    ID=$(docker ps | grep "$CONTAINER_NAME" | awk '{print $1}')
    if [[ ! -z "$ID" ]]; then
        docker stop $ID > /dev/null
    fi

    # Check if an existing DB volume exists
    if [[ -d $HOST_DIR ]]; then
        echo "-----> Reusing $CONTAINER_NAME data"
    else
        mkdir -p $HOST_DIR
        chown -R dokku:dokku $HOST_DIR
    fi
    VOLUME="$HOST_DIR:/var/lib/mariadb"

    # Launch container
    docker run -p 3306:3306 -v $VOLUME -e MARIADB_DATABASE=$APP \
      --name=$CONTAINER_NAME -d partlab/ubuntu-mariadb \
      /usr/local/bin/run 

    # Link to a potential existing app
    dokku mariadb:link $APP $APP
    echo "-----> MariaDB container created: $CONTAINER_NAME"
    sleep 1
    dokku mariadb:info $APP
    ;;

  mariadb:delete)
    # Stop the container
    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
    if [[ ! -z $ID ]]; then
        docker stop $ID > /dev/null
        docker rm $ID  > /dev/null
    fi
    # Remove persistent volume
    if [[ -d $HOST_DIR ]]; then
        rm -rf $HOST_DIR
    fi

    # unlink this container as "mariadb"
    dokku link:delete "$APP" "$CONTAINER_NAME" "$PLUGIN_NAME"
    dokku config:unset "$APP" $ENVVAR_NAME
    echo "-----> MariaDB container deleted: $CONTAINER_NAME"
    ;;

  mariadb:info)
    ID=$(docker ps -a | grep "$CONTAINER_NAME" | awk '{print $1}')
    IP=$(docker inspect $ID | grep IPAddress | cut -d '"' -f 4)
    echo
    echo "       Host: ${IP}"
    echo "       Private ports: 3306"
    echo "       Username: root"
    echo "       Database: ${APP}"
    echo
    ;;

  mariadb:link)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
            echo "You must specify a container name"
            exit 1
        fi
        CONTAINER_NAME="${PLUGIN_NAME}_${3}"

        # link this container as "mariadb"
        dokku link:create "$APP" "$CONTAINER_NAME" "$PLUGIN_NAME"

        # figure out IP to set env var
        ID=$(docker ps -a | grep "$CONTAINER_NAME" | awk '{print $1}')
        IP=$(docker inspect $ID | grep IPAddress | cut -d '"' -f 4)
        dokku config:set "$APP" $ENVVAR_NAME="mysql://root@\$MARIADB_PORT_3306_TCP_ADDR:\$MARIADB_PORT_3306_TCP_PORT/$APP"
        echo "-----> $APP linked to $CONTAINER_NAME container"
    fi
    ;;

  mariadb:logs)
    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
    docker logs $ID | tail -n 100
    ;;

  help)
    cat && cat<<EOF
    mariadb:create <app>                            Create a MariaDB container
    mariadb:delete <app>                            Delete specified MariaDB container
    mariadb:info <app>                              Display container informations
    mariadb:link <app> <container>                  Link an app to a MariaDB container
    mariadb:logs <app>                              Display last logs from MariaDB container
EOF
    ;;

esac
